#!/bin/sh

TIMEOUT=30
SLEEP=3

sta_err=0

while true; do
	if [ $(iwinfo | grep -c "ESSID: unknown") -ge 1 ]; then
		let sta_err=$sta_err+1
		if [ $((sta_err * SLEEP)) -ge SLEEP ]; then
			cp /etc/config/wireless_AP /etc/config/wireless
			wifi up
			sleep $SLEEP
			#will retry sta connection after reboot or wifi up
			cp /etc/config/wireless_APSTA /etc/config/wireless
			let sta_err=0
		fi
	else
		let sta_err=0
	fi
	sleep $SLEEP
done

