#!/bin/sh

if [ $(cat /etc/config/wireless | grep -c "mode sta") -ge 1 ]; then
	cat /root/wireless.common > /etc/config/wireless_AP
	cat /root/wireless.ap >> /etc/config/wireless_AP
	sta_fix
else
	cat /root/wireless.common > /etc/config/wireless
	cat /root/wireless.ap >> /etc/config/wireless
fi


