#!/bash/sh

SLEEP=5

if [ $(cat /etc/config/wireless | grep -c "mode sta") -ge 1 ]; then
	cat /root/wireless.common > /etc/config/wireless
	cat /root/wireless.ap >> /etc/config/wireless
	cat /root/wireless.sta >> /etc/config/wireless
else
	cat /root/wireless.common > /etc/config/wireless
	cat /root/wireless.ap >> /etc/config/wireless
fi

cat /root/wireless.common > /etc/config/wireless_AP
cat /root/wireless.ap >> /etc/config/wireless_AP

cat /root/wireless.common > /etc/config/wireless_APSTA
cat /root/wireless.ap >> /etc/config/wireless_APSTA
cat /root/wireless.sta >> /etc/config/wireless_APSTA

wifi up
sleep $SLEEP
